#- name: Test only these tasks
#  hosts: jolnvms32
#  become: yes
#  vars:
#    cassandra_home_dir: /CASSANDRA
#    cassandra_home_bin: apache-cassandra-3.11.10
#
#    cassandra_conf_file: "{{ cassandra_home_dir }}/{{ cassandra_home_bin }}/conf/cassandra.yaml"
#    cassandra_conf_cluster_name: "cluster_name: \'JOSuseCluster1\'"
#    cassandra_conf_data_file_dir: "data_file_directories:"
#    cassandra_conf_data_file_dir_l1: "    - {{ cassandra_home_dir }}/data"
#    cassandra_conf_commitlog_dir: "commitlog_directory: {{ cassandra_home_dir }}/commitlog"
#    cassandra_conf_saved_cache_dir: "saved_caches_directory: {{ cassandra_home_dir }}/saved_caches"
#    cassandra_conf_hints_dir: "hints_directory:  {{ cassandra_home_dir }}/hints"
#    cassandra_conf_seeds: "          - seeds: \"jolnvms31\""
#    cassandra_conf_listen_address: "listen_address: "
#    cassandra_conf_rpc_address: "rpc_address: "
#  tasks:
    - name: Print cassandra conf file
      debug:
        msg: "{{ cassandra_conf_file }}"
    - name: Print cassandra parameters to set
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ cassandra_conf_cluster_name }}"
        - "{{ cassandra_conf_data_file_dir }}"
        - "{{ cassandra_conf_data_file_dir_l1 }}"
        - "{{ cassandra_conf_commitlog_dir }}"
        - "{{ cassandra_conf_saved_cache_dir }}"
        - "{{ cassandra_conf_hints_dir }}"
        - "{{ cassandra_conf_seeds }}"
        - "{{ cassandra_conf_listen_address }}"
        - "{{ cassandra_conf_rpc_address }}"
    - name: Modyfing parameter ... {{ cassandra_conf_cluster_name }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*cluster_name:.*"
        line: "{{ cassandra_conf_cluster_name }}"
    - name: Modyfing parameter ... {{ cassandra_conf_data_file_dir }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*data_file_directories:.*"
        line: "{{ cassandra_conf_data_file_dir }}"
    - name: Modyfing parameter ... {{ cassandra_conf_data_file_dir_l1 }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        insertafter: ".*data_file_directories:.*"
        line: "{{ cassandra_conf_data_file_dir_l1 }}"
    - name: Modyfing parameter ... {{ cassandra_conf_commitlog_dir }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*commitlog_directory:.*"
        line: "{{ cassandra_conf_commitlog_dir }}"
    - name: Modyfing parameter ... {{ cassandra_conf_saved_cache_dir }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*saved_caches_directory:.*"
        line: "{{ cassandra_conf_saved_cache_dir }}"
    - name: Modyfing parameter ... {{ cassandra_conf_hints_dir }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*hints_directory:.*"
        line: "{{ cassandra_conf_hints_dir }}"
    - name: Modyfing parameter ... {{ cassandra_conf_seeds }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: ".*- seeds:.*"
        line: "{{ cassandra_conf_seeds }}"
    - name: Modyfing parameter ... {{ cassandra_conf_listen_address }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: "^listen_address:.*"
        line: "{{ cassandra_conf_listen_address }}{{ ansible_ssh_host }}"
    - name: Modyfing parameter ... {{ cassandra_conf_rpc_address }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: "^rpc_address:.*"
        line: "{{ cassandra_conf_rpc_address }}{{ ansible_ssh_host }}"
    - name: Modyfing parameter ... {{ cassandra_conf_snitch_value }}
      lineinfile:
        path: "{{ cassandra_conf_file }}"
        state: present
        regexp: "{{ cassandra_conf_snitch_regex }}"
        line: "{{ cassandra_conf_snitch_value }}"
