---
# tasks file for roles/cassandra_idemia/cassandra_repository
- name: Ensure Cassandra yum repository exists (RedHat)
  yum_repository:
      name: "cassandra-{{ cassandra_version }}"
      description: "Official Cassandra {{ cassandra_version }} yum repo"
      baseurl: "https://www.apache.org/dist/cassandra/redhat/{{ cassandra_version }}/"
      gpgcheck: 1
      gpgkey: "https://www.apache.org/dist/cassandra/KEYS"
  when: ansible_os_family == "RedHat"

- name: Install debian packages (Debian & Ubuntu)
  apt:
    name: "{{ debian_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Time Server (Debian & Ubuntu)
  apt:
    name: "{{ time_server_pkg }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add apt key for Cassandra repository (Debian & Ubuntu)
  apt_key:
    url: https://www.apache.org/dist/cassandra/KEYS
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Cassandra apt repository exists (Debian & Ubuntu)
  apt_repository:
    repo: "deb http://www.apache.org/dist/cassandra/debian {{ cassandra_version }} main"
    state: present
    #    filename: "cassandra-{{ cassandra_version }}"
    filename: "cassandra.sources"
  when: ansible_os_family == "Debian"

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

