---
# tasks file for roles/cassandra_idemia/cassandra_install
- name: Dowload conf file from git
  get_url:
    url: "{{ url_with_conf_file1 }}"
    dest: "{{ url_with_conf_file1_dest }}"
    mode: 0644
  delegate_to: 127.0.0.1
  become: no
- name: Deliver {{ cassandra_conf_file }} file
  template:
    src: templates/cassandra.j2
    dest: "{{ cassandra_conf_file }}"
    #dest: /tmp/cassandra.yaml
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0644
- name: Deliver {{ cassandra_rack_conf_file }} file
  template:
    src: templates/cassandra-rackdc.properties.j2
    dest: "{{ cassandra_rack_conf_file }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0644
  when: 'ansible_hostname == host_from_dc2|string'
